env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 100
    lines: 200
  padding:
    x: 2
    y: 0
  dynamic_padding: false
  decorations: full
  startup_mode: Maximized

font:
  normal:
    family: "DroidSansMono Nerd Font"
    style: "Book"
  size: 13
  glyph_offset:
    x: 0
    y: 1

schemes:
  edge_dark:  &edge_dark
    primary:
      background: "0x2c2e34"
      foreground: "0xc5cdd9"

    normal:
      black:      "0x363944"
      red:        "0xec7279"
      green:      "0xa0c980"
      yellow:     "0xdeb974"
      blue:       "0x6cb6eb"
      magenta:    "0xd38aea"
      cyan:       "0x5dbbc1"
      white:      "0xc5cdd9"

    bright:
      black:      "0x363a49"
      red:        "0xec7279"
      green:      "0xa0c980"
      yellow:     "0xdeb974"
      blue:       "0x6cb6eb"
      magenta:    "0xd38aea"
      cyan:       "0x5dbbc1"
      white:      "0xc5cdd9"

    cursor:
      cursor:     "0xc5cdd9"
      text:       "0x2c2e34"

colors: *edge_dark

cursor:
  style: Block

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - tmux new -As alacritty

key_bindings:
# Base binds
  - { key: F1,                                  chars: "\x1bOP"      }
  - { key: F2,                                  chars: "\x1bOQ"      }
  - { key: F3,                                  chars: "\x1bOR"      }
  - { key: F4,                                  chars: "\x1bOS"      }
  - { key: F5,                                  chars: "\x1b[15~"    }
  - { key: F6,                                  chars: "\x1b[17~"    }
  - { key: F7,                                  chars: "\x1b[18~"    }
  - { key: F8,                                  chars: "\x1b[19~"    }
  - { key: F9,                                  chars: "\x1b[20~"    }
  - { key: F10,                                 chars: "\x1b[21~"    }
  - { key: F11,                                 chars: "\x1b[23~"    }
  - { key: F12,                                 chars: "\x1b[24~"    }
  - { key: F1,       mods: Shift,               chars: "\x1b[1;2P"   }
  - { key: F2,       mods: Shift,               chars: "\x1b[1;2Q"   }
  - { key: F3,       mods: Shift,               chars: "\x1b[1;2R"   }
  - { key: F4,       mods: Shift,               chars: "\x1b[1;2S"   }
  - { key: F5,       mods: Shift,               chars: "\x1b[15;2~"  }
  - { key: F6,       mods: Shift,               chars: "\x1b[17;2~"  }
  - { key: F7,       mods: Shift,               chars: "\x1b[18;2~"  }
  - { key: F8,       mods: Shift,               chars: "\x1b[19;2~"  }
  - { key: F9,       mods: Shift,               chars: "\x1b[20;2~"  }
  - { key: F10,      mods: Shift,               chars: "\x1b[21;2~"  }
  - { key: F11,      mods: Shift,               chars: "\x1b[23;2~"  }
  - { key: F12,      mods: Shift,               chars: "\x1b[24;2~"  }
  - { key: F1,       mods: Control,             chars: "\x1b[1;5P"   }
  - { key: F2,       mods: Control,             chars: "\x1b[1;5Q"   }
  - { key: F3,       mods: Control,             chars: "\x1b[1;5R"   }
  - { key: F4,       mods: Control,             chars: "\x1b[1;5S"   }
  - { key: F5,       mods: Control,             chars: "\x1b[15;5~"  }
  - { key: F6,       mods: Control,             chars: "\x1b[17;5~"  }
  - { key: F7,       mods: Control,             chars: "\x1b[18;5~"  }
  - { key: F8,       mods: Control,             chars: "\x1b[19;5~"  }
  - { key: F9,       mods: Control,             chars: "\x1b[20;5~"  }
  - { key: F10,      mods: Control,             chars: "\x1b[21;5~"  }
  - { key: F11,      mods: Control,             chars: "\x1b[23;5~"  }
  - { key: F12,      mods: Control,             chars: "\x1b[24;5~"  }
  - { key: F1,       mods: Alt,                 chars: "\x1b[1;6P"   }
  - { key: F2,       mods: Alt,                 chars: "\x1b[1;6Q"   }
  - { key: F3,       mods: Alt,                 chars: "\x1b[1;6R"   }
  - { key: F4,       mods: Alt,                 chars: "\x1b[1;6S"   }
  - { key: F5,       mods: Alt,                 chars: "\x1b[15;6~"  }
  - { key: F6,       mods: Alt,                 chars: "\x1b[17;6~"  }
  - { key: F7,       mods: Alt,                 chars: "\x1b[18;6~"  }
  - { key: F8,       mods: Alt,                 chars: "\x1b[19;6~"  }
  - { key: F9,       mods: Alt,                 chars: "\x1b[20;6~"  }
  - { key: F10,      mods: Alt,                 chars: "\x1b[21;6~"  }
  - { key: F11,      mods: Alt,                 chars: "\x1b[23;6~"  }
  - { key: F12,      mods: Alt,                 chars: "\x1b[24;6~"  }
  - { key: F1,       mods: Command,             chars: "\x1b[1;3P"   }
  - { key: F2,       mods: Command,             chars: "\x1b[1;3Q"   }
  - { key: F3,       mods: Command,             chars: "\x1b[1;3R"   }
  - { key: F4,       mods: Command,             chars: "\x1b[1;3S"   }
  - { key: F5,       mods: Command,             chars: "\x1b[15;3~"  }
  - { key: F6,       mods: Command,             chars: "\x1b[17;3~"  }
  - { key: F7,       mods: Command,             chars: "\x1b[18;3~"  }
  - { key: F8,       mods: Command,             chars: "\x1b[19;3~"  }
  - { key: F9,       mods: Command,             chars: "\x1b[20;3~"  }
  - { key: F10,      mods: Command,             chars: "\x1b[21;3~"  }
  - { key: F11,      mods: Command,             chars: "\x1b[23;3~"  }
  - { key: F12,      mods: Command,             chars: "\x1b[24;3~"  }
# Jump between words
  - { key: Right,    mods: Alt,                 chars: "\x1BF"       }
  - { key: Left,     mods: Alt,                 chars: "\x1BB"       }
# Iterm2 binds
  - { key: D,        mods: Command,             chars: "\x06\x76"    }
  - { key: D,        mods: Command|Shift,       chars: "\x06\x73"    }
  - { key: W,        mods: Command,             chars: "\x06\x78"    }
  - { key: T,        mods: Command,             chars: "\x06\x63"    }
# Binds for neovim jumps between tabs and windows
  - { key: H,        mods: Control,             chars: "\x08"        }
  - { key: J,        mods: Control,             chars: "\x0a"        }
  - { key: K,        mods: Control,             chars: "\x0b"        }
  - { key: L,        mods: Control,             chars: "\x0c"        }
  - { key: H,        mods: Alt,                 chars: "\x1b\x68"    }
  - { key: J,        mods: Alt,                 chars: "\x1b\x6a"    }
  - { key: K,        mods: Alt,                 chars: "\x1b\x6b"    }
  - { key: L,        mods: Alt,                 chars: "\x1b\x6c"    }
# Select window
  - { key: Key1,     mods: Command,             chars: "\x06\x31"    }
  - { key: Key2,     mods: Command,             chars: "\x06\x32"    }
  - { key: Key3,     mods: Command,             chars: "\x06\x33"    }
  - { key: Key4,     mods: Command,             chars: "\x06\x34"    }
  - { key: Key5,     mods: Command,             chars: "\x06\x35"    }
  - { key: Key6,     mods: Command,             chars: "\x06\x36"    }
  - { key: Key7,     mods: Command,             chars: "\x06\x37"    }
  - { key: Key8,     mods: Command,             chars: "\x06\x38"    }
  - { key: Key9,     mods: Command,             chars: "\x06\x39"    }
  - { key: Key0,     mods: Command,             chars: "\x06\x30"    }
  - { key: Minus,    mods: Command,             chars: "\x06\x2d"    }
  - { key: Equals,   mods: Command,             chars: "\x06\x3d"    }
  - { key: Equals,   mods: Shift|Command,       chars: "\x06\x2b"    }
# Select pane
  - { key: H,        mods: Command,             chars: "\x06\x68"    }
  - { key: J,        mods: Command,             chars: "\x06\x6a"    }
  - { key: K,        mods: Command,             chars: "\x06\x6b"    }
  - { key: L,        mods: Command,             chars: "\x06\x6c"    }
# Resize pane
  - { key: H,        mods: Alt|Command,         chars: "\x06\x48"    }
  - { key: J,        mods: Alt|Command,         chars: "\x06\x4a"    }
  - { key: K,        mods: Alt|Command,         chars: "\x06\x4b"    }
  - { key: L,        mods: Alt|Command,         chars: "\x06\x4c"    }

  - { key: J,        mods: Shift|Command,       chars: "\x1b[B"      }
  - { key: K,        mods: Shift|Command,       chars: "\x1b[A"      }
  - { key: LBracket, mods: Command,             chars: "\x06\x5b"    }
  - { key: 3,        mods: Shift|Alt,           chars: "\xe2\x80\xb9"}
